---
- name: Create compose directory
  file:
    path: "{{ awx_docker_compose_dir }}"
    state: directory
    mode: 0755

- name: Create awx projects directory
  file:
    path: "{{ awx_project_data_dir }}"
    state: directory
    mode: 0755

- name: Create awx inventory directory
  file:
    path: "{{ awx_inventory_dir }}"
    state: directory
    mode: 0755

- name: Create awx postgres data directory
  file:
    path: "{{ postgres_data_dir }}"
    state: directory
    mode: 0755

- name: Create Docker Compose Configuration
  template:
    src: "{{ item }}.j2"
    dest: "{{ awx_docker_compose_dir }}/{{ item }}"
    mode: 0600
  loop:
    - environment.sh
    - credentials.py
    - docker-compose.yml
  register: awx_compose_config

- name: Create SECRET_KEY file
  copy:
    content: "{{ awx_secret_key }}"
    dest: "{{ awx_docker_compose_dir }}/SECRET_KEY"
    mode: 0600

- name: Start docker services
  docker_service:
    project_src: "{{ awx_docker_compose_dir }}"
