---
- name: Create compose directory
  file:
    path: "{{ awx_docker_compose_dir }}"
    state: directory
    mode: 0755

- name: Create awx projects directory
  file:
    path: "{{ awx_project_data_dir }}"
    state: directory
    mode: 0755

- name: Create awx inventory directory
  file:
    path: "{{ awx_inventory_dir }}"
    state: directory
    mode: 0755

- name: Create awx postgres data directory
  file:
    path: "{{ postgres_data_dir }}"
    state: directory
    mode: 0755

- name: Create awx home directory
  file:
    path: "{{ awx_install_path }}"
    state: directory
    mode: 0755

- name: Clone awx git repository
  git:
    repo: "{{ awx_git_url }}"
    dest: "{{ awx_install_path }}/awx"
    version: "{{ awx_git_revison }}"
    force: yes

- name: Update awx template configs
  copy:
    src: "{{ item }}"
    dest: "{{ awx_install_path }}/awx/installer/roles/local_docker/templates/{{ item }}"
    mode: 0644
  loop:
    - environment.sh.j2
    - credentials.py.j2
    - nginx.conf.j2

- block:
  - name: Update non-nginx image_build templates
    copy:
      src: "{{ item }}"
      dest: "{{ awx_install_path }}/awx/installer/roles/image_build/templates/{{ item }}"
      mode: 0644
    loop:
      - Dockerfile.j2
      - Dockerfile.task.j2

  - name: Update non-nginx compose.yml
    copy:
      src: compose.yml
      dest: "{{ awx_install_path }}/awx/installer/roles/local_docker/tasks/compose.yml"
      mode: 0644

  - name: Update non-nginx Caddyfile.j2
    template:
      src: Caddyfile.j2
      dest: "{{ awx_install_path }}/awx/installer/roles/local_docker/templates/Caddyfile.j2"
      mode: 0644
  when: not awx_enable_nginx|bool

- name: Update docker-compose.yml template
  template:
    src: docker-compose.yml.j2
    dest: "{{ awx_install_path }}/awx/installer/roles/local_docker/templates/docker-compose.yml.j2"
    mode: 0644

- name: Create SECRET_KEY file
  copy:
    content: "{{ awx_secret_key }}"
    dest: "{{ awx_docker_compose_dir }}/SECRET_KEY"
    mode: 0600

- name: Update awx installer inventory
  template:
    src: inventory.j2
    dest: "{{ awx_install_path }}/awx/installer/inventory"
    mode: 0600

- name: Update awx supervisor.conf
  template:
    src: supervisor.conf.j2
    dest: "{{ awx_install_path }}/awx/installer/roles/image_build/files/supervisor.conf"
    mode: 0644

- block:
  - name: Create custom assets directories
    file:
      path: "{{ awx_install_path }}/awx-logos/awx/ui/client/assets"
      state: directory
      mode: 0755
      recurse: yes

  - name: Deploy custom assets
    copy:
      src: "assets/{{ item }}"
      dest: "{{ awx_install_path }}/awx-logos/awx/ui/client/assets/{{ item }}"
      mode: 0644
    loop: "{{ awx_custom_assets_files | d([]) }}"
  when: awx_custom_assets|d(false)|bool

- name: Check if awx deployed
  docker_container_info:
    name: awx_web
  register: docker_result

- name: Run awx installer
  shell: "{{ awx_default_conda_path }}/bin/ansible-playbook -i inventory install.yml"
  args:
      chdir: "{{ awx_install_path }}/awx/installer"
  ignore_errors: no
  register: installer_results
  when: not docker_result.exists
